### ISSUE TITLE
Does not work with projects with multiple targets.

### ISSUE THREAD

**Issue by kennytm** [White-Oak/cargo-clippy#2]
Steps:

* Create a project with multiple targets, e.g. a library and a binary:

    ```
    project/
        Cargo.toml
        src/
            lib.rs
            bin/
                run_project.rs
    ```

* Run `cargo clippy --lib`
* The program fails with:

    ```
    error: extra arguments to `rustc` can only be passed to one target, consider filtering
    the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
    error: 
    ```

---

Directly calling `cargo rustc --lib -- -L ~/.cargo/rust-clippy/target/release/ -Z extra-plugins=clippy -Zno-trans` does work. But cargo-clippy ignores all extra arguments. 

`cargo-clippy` should forward the `--lib`, `--bin NAME`, `--test NAME` and `--example NAME` and `--bench NAME` arguments to `cargo rustc`.

----

```sh
$ rustc -vV
rustc 1.11.0-nightly (7d2f75a95 2016-06-09)
binary: rustc
commit-hash: 7d2f75a953b5645d3a336b2978b48b60d310bf54
commit-date: 2016-06-09
host: x86_64-apple-darwin
release: 1.11.0-nightly
$ cargo -vV
cargo 0.12.0-nightly (761ea2d 2016-06-09)
```

**Comment by White-Oak** [comment]
@kennytm Thanks for the detailed bug report, but unfortunately, this crate is **deprecated** in favor of official [Clippy](github.com/Manishearth/rust-clippy) as they managed to install `cargo clippy` command as the part of `cargo install clippy` with the merge of https://github.com/Manishearth/rust-clippy/pull/681.

I believe their version is more feature-complete and more well-supported, so I yanked all of my versions and edited README.

**Comment by kennytm** [comment]
OK thanks.
